// Code generated by protoc-gen-go.
// source: peer/processMessage.proto
// DO NOT EDIT!

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type QueryBlocks struct {
	BlockIndex uint64 `protobuf:"varint,1,opt,name=BlockIndex" json:"BlockIndex,omitempty"`
	ChannelID  string `protobuf:"bytes,2,opt,name=ChannelID" json:"ChannelID,omitempty"`
}

func (m *QueryBlocks) Reset()                    { *m = QueryBlocks{} }
func (m *QueryBlocks) String() string            { return proto.CompactTextString(m) }
func (*QueryBlocks) ProtoMessage()               {}
func (*QueryBlocks) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type ChannelMessage struct {
	ChannelInput []*MessageInput `protobuf:"bytes,1,rep,name=ChannelInput" json:"ChannelInput,omitempty"`
}

func (m *ChannelMessage) Reset()                    { *m = ChannelMessage{} }
func (m *ChannelMessage) String() string            { return proto.CompactTextString(m) }
func (*ChannelMessage) ProtoMessage()               {}
func (*ChannelMessage) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *ChannelMessage) GetChannelInput() []*MessageInput {
	if m != nil {
		return m.ChannelInput
	}
	return nil
}

type MessageInput struct {
	PeerIp    string    `protobuf:"bytes,1,opt,name=PeerIp" json:"PeerIp,omitempty"`
	Height    uint64    `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	PeerName  string    `protobuf:"bytes,3,opt,name=PeerName" json:"PeerName,omitempty"`
	Mblocks   []*Mblock `protobuf:"bytes,4,rep,name=Mblocks" json:"Mblocks,omitempty"`
	ChannelID string    `protobuf:"bytes,5,opt,name=ChannelID" json:"ChannelID,omitempty"`
}

func (m *MessageInput) Reset()                    { *m = MessageInput{} }
func (m *MessageInput) String() string            { return proto.CompactTextString(m) }
func (*MessageInput) ProtoMessage()               {}
func (*MessageInput) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *MessageInput) GetMblocks() []*Mblock {
	if m != nil {
		return m.Mblocks
	}
	return nil
}

type Mblock struct {
	Header   *MblockHeader   `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Data     *MblockData     `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	Metadata *MblockMetadata `protobuf:"bytes,3,opt,name=Metadata" json:"Metadata,omitempty"`
}

func (m *Mblock) Reset()                    { *m = Mblock{} }
func (m *Mblock) String() string            { return proto.CompactTextString(m) }
func (*Mblock) ProtoMessage()               {}
func (*Mblock) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *Mblock) GetHeader() *MblockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Mblock) GetData() *MblockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Mblock) GetMetadata() *MblockMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type MblockHeader struct {
	Number       uint64 `protobuf:"varint,1,opt,name=Number" json:"Number,omitempty"`
	PreviousHash string `protobuf:"bytes,2,opt,name=PreviousHash" json:"PreviousHash,omitempty"`
	DataHash     string `protobuf:"bytes,3,opt,name=DataHash" json:"DataHash,omitempty"`
	NowHash      string `protobuf:"bytes,4,opt,name=NowHash" json:"NowHash,omitempty"`
}

func (m *MblockHeader) Reset()                    { *m = MblockHeader{} }
func (m *MblockHeader) String() string            { return proto.CompactTextString(m) }
func (*MblockHeader) ProtoMessage()               {}
func (*MblockHeader) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

type MblockData struct {
	Datas []*TransData `protobuf:"bytes,1,rep,name=Datas" json:"Datas,omitempty"`
}

func (m *MblockData) Reset()                    { *m = MblockData{} }
func (m *MblockData) String() string            { return proto.CompactTextString(m) }
func (*MblockData) ProtoMessage()               {}
func (*MblockData) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *MblockData) GetDatas() []*TransData {
	if m != nil {
		return m.Datas
	}
	return nil
}

type TransData struct {
	Txid    string                      `protobuf:"bytes,1,opt,name=Txid" json:"Txid,omitempty"`
	ChainID string                      `protobuf:"bytes,2,opt,name=ChainID" json:"ChainID,omitempty"`
	Time    *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=Time" json:"Time,omitempty"`
}

func (m *TransData) Reset()                    { *m = TransData{} }
func (m *TransData) String() string            { return proto.CompactTextString(m) }
func (*TransData) ProtoMessage()               {}
func (*TransData) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *TransData) GetTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type MblockMetadata struct {
	Metadata []string `protobuf:"bytes,1,rep,name=Metadata" json:"Metadata,omitempty"`
}

func (m *MblockMetadata) Reset()                    { *m = MblockMetadata{} }
func (m *MblockMetadata) String() string            { return proto.CompactTextString(m) }
func (*MblockMetadata) ProtoMessage()               {}
func (*MblockMetadata) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

type MessageOutput struct {
	Output string `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *MessageOutput) Reset()                    { *m = MessageOutput{} }
func (m *MessageOutput) String() string            { return proto.CompactTextString(m) }
func (*MessageOutput) ProtoMessage()               {}
func (*MessageOutput) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func init() {
	proto.RegisterType((*QueryBlocks)(nil), "protos.QueryBlocks")
	proto.RegisterType((*ChannelMessage)(nil), "protos.ChannelMessage")
	proto.RegisterType((*MessageInput)(nil), "protos.MessageInput")
	proto.RegisterType((*Mblock)(nil), "protos.Mblock")
	proto.RegisterType((*MblockHeader)(nil), "protos.MblockHeader")
	proto.RegisterType((*MblockData)(nil), "protos.MblockData")
	proto.RegisterType((*TransData)(nil), "protos.TransData")
	proto.RegisterType((*MblockMetadata)(nil), "protos.MblockMetadata")
	proto.RegisterType((*MessageOutput)(nil), "protos.MessageOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for StatusPeer service

type StatusPeerClient interface {
	ProcessMessage(ctx context.Context, in *ChannelMessage, opts ...grpc.CallOption) (*MessageOutput, error)
}

type statusPeerClient struct {
	cc *grpc.ClientConn
}

func NewStatusPeerClient(cc *grpc.ClientConn) StatusPeerClient {
	return &statusPeerClient{cc}
}

func (c *statusPeerClient) ProcessMessage(ctx context.Context, in *ChannelMessage, opts ...grpc.CallOption) (*MessageOutput, error) {
	out := new(MessageOutput)
	err := grpc.Invoke(ctx, "/protos.statusPeer/ProcessMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StatusPeer service

type StatusPeerServer interface {
	ProcessMessage(context.Context, *ChannelMessage) (*MessageOutput, error)
}

func RegisterStatusPeerServer(s *grpc.Server, srv StatusPeerServer) {
	s.RegisterService(&_StatusPeer_serviceDesc, srv)
}

func _StatusPeer_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusPeerServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.statusPeer/ProcessMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusPeerServer).ProcessMessage(ctx, req.(*ChannelMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatusPeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.statusPeer",
	HandlerType: (*StatusPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _StatusPeer_ProcessMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor6,
}

// Client API for QueryPeer service

type QueryPeerClient interface {
	QueryMessage(ctx context.Context, in *QueryBlocks, opts ...grpc.CallOption) (*Mblock, error)
}

type queryPeerClient struct {
	cc *grpc.ClientConn
}

func NewQueryPeerClient(cc *grpc.ClientConn) QueryPeerClient {
	return &queryPeerClient{cc}
}

func (c *queryPeerClient) QueryMessage(ctx context.Context, in *QueryBlocks, opts ...grpc.CallOption) (*Mblock, error) {
	out := new(Mblock)
	err := grpc.Invoke(ctx, "/protos.queryPeer/QueryMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QueryPeer service

type QueryPeerServer interface {
	QueryMessage(context.Context, *QueryBlocks) (*Mblock, error)
}

func RegisterQueryPeerServer(s *grpc.Server, srv QueryPeerServer) {
	s.RegisterService(&_QueryPeer_serviceDesc, srv)
}

func _QueryPeer_QueryMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlocks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryPeerServer).QueryMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.queryPeer/QueryMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryPeerServer).QueryMessage(ctx, req.(*QueryBlocks))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryPeer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.queryPeer",
	HandlerType: (*QueryPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryMessage",
			Handler:    _QueryPeer_QueryMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor6,
}

func init() { proto.RegisterFile("peer/processMessage.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0x68, 0xd6, 0x2d, 0xb7, 0xa5, 0x12, 0x06, 0xa6, 0x50, 0x21, 0xa8, 0xf2, 0xc0, 0x8a,
	0x98, 0x12, 0x29, 0x68, 0x12, 0xaf, 0x74, 0x7b, 0x58, 0x41, 0xed, 0x4a, 0xd4, 0x27, 0xde, 0x9c,
	0xd6, 0x4b, 0x22, 0xda, 0x24, 0xd8, 0x0e, 0x6c, 0x6f, 0xfc, 0x06, 0x7e, 0x02, 0xbf, 0x14, 0xf9,
	0xc6, 0xce, 0x92, 0x3e, 0x25, 0xe7, 0x9e, 0x93, 0xf8, 0xdc, 0x2f, 0xc3, 0xab, 0x92, 0x31, 0x1e,
	0x94, 0xbc, 0xd8, 0x30, 0x21, 0x16, 0x4c, 0x08, 0x9a, 0x30, 0xbf, 0xe4, 0x85, 0x2c, 0x48, 0x1f,
	0x1f, 0x62, 0xfc, 0x36, 0x29, 0x8a, 0x64, 0xc7, 0x02, 0x84, 0x71, 0x75, 0x17, 0xc8, 0x6c, 0xcf,
	0x84, 0xa4, 0xfb, 0xb2, 0x16, 0x7a, 0x5f, 0x61, 0xf0, 0xad, 0x62, 0xfc, 0x61, 0xb6, 0x2b, 0x36,
	0x3f, 0x04, 0x79, 0x03, 0x80, 0x6f, 0xf3, 0x7c, 0xcb, 0xee, 0x5d, 0x6b, 0x62, 0x4d, 0xed, 0xa8,
	0x15, 0x21, 0xaf, 0xc1, 0xb9, 0x4a, 0x69, 0x9e, 0xb3, 0xdd, 0xfc, 0xda, 0x7d, 0x32, 0xb1, 0xa6,
	0x4e, 0xf4, 0x18, 0xf0, 0xbe, 0xc0, 0x48, 0x03, 0xed, 0x86, 0x7c, 0x82, 0xa1, 0xa1, 0xf3, 0xb2,
	0x92, 0xae, 0x35, 0xe9, 0x4d, 0x07, 0xe1, 0x8b, 0xfa, 0x70, 0xe1, 0x6b, 0x19, 0x72, 0x51, 0x47,
	0xe9, 0xfd, 0xb3, 0x60, 0xd8, 0xa6, 0xc9, 0x19, 0xf4, 0x57, 0x8c, 0xf1, 0x79, 0x89, 0xb6, 0x9c,
	0x48, 0x23, 0x15, 0xbf, 0x61, 0x59, 0x92, 0x4a, 0xf4, 0x63, 0x47, 0x1a, 0x91, 0x31, 0x9c, 0x2a,
	0xc5, 0x92, 0xee, 0x99, 0xdb, 0xc3, 0x2f, 0x1a, 0x4c, 0xa6, 0x70, 0xb2, 0x88, 0x31, 0x63, 0xd7,
	0x46, 0x47, 0xa3, 0xc6, 0x11, 0x86, 0x23, 0x43, 0x77, 0x13, 0x3e, 0x3e, 0x4c, 0xf8, 0xaf, 0x05,
	0xfd, 0x5a, 0x49, 0x2e, 0x94, 0x0d, 0xba, 0x65, 0x1c, 0xed, 0xb5, 0x73, 0x44, 0xbe, 0xe6, 0x22,
	0xad, 0x21, 0xef, 0xc0, 0xbe, 0xa6, 0x92, 0xa2, 0xe5, 0x41, 0x48, 0xba, 0x5a, 0xc5, 0x44, 0xc8,
	0x93, 0x10, 0x4e, 0x17, 0x4c, 0xd2, 0xad, 0xd2, 0xf6, 0x50, 0x7b, 0xd6, 0xd5, 0x1a, 0x36, 0x6a,
	0x74, 0xde, 0x1f, 0x55, 0xb9, 0xd6, 0xa1, 0xaa, 0x42, 0xcb, 0x6a, 0x1f, 0x6b, 0x6b, 0x76, 0xa4,
	0x11, 0xf1, 0x60, 0xb8, 0xe2, 0xec, 0x57, 0x56, 0x54, 0xe2, 0x86, 0x8a, 0x54, 0xf7, 0xb3, 0x13,
	0x53, 0x55, 0x54, 0x46, 0x90, 0xd7, 0x55, 0x34, 0x98, 0xb8, 0x70, 0xb2, 0x2c, 0x7e, 0x23, 0x65,
	0x23, 0x65, 0xa0, 0x77, 0x09, 0xf0, 0x98, 0x0a, 0x39, 0x87, 0x63, 0xf5, 0x14, 0xba, 0xfb, 0xcf,
	0x4c, 0x06, 0x6b, 0x4e, 0x73, 0x81, 0xc9, 0xd6, 0xbc, 0x97, 0x81, 0xd3, 0xc4, 0x08, 0x01, 0x7b,
	0x7d, 0x9f, 0x6d, 0x75, 0xb7, 0xf1, 0x5d, 0x9d, 0x78, 0x95, 0xd2, 0x2c, 0x6f, 0x86, 0xcf, 0x40,
	0xe2, 0x83, 0xbd, 0xce, 0x74, 0xa7, 0x07, 0xe1, 0xd8, 0xaf, 0xe7, 0xde, 0x37, 0x73, 0xef, 0xaf,
	0xcd, 0xdc, 0x47, 0xa8, 0xf3, 0x2e, 0x60, 0xd4, 0x2d, 0xa0, 0xca, 0xb4, 0x29, 0xb5, 0x32, 0xea,
	0xb4, 0x4a, 0x7a, 0x0e, 0x4f, 0xf5, 0x2c, 0xde, 0x56, 0x52, 0x0f, 0x63, 0x81, 0x6f, 0x66, 0x18,
	0x6b, 0x14, 0xde, 0x02, 0x08, 0x49, 0x65, 0x25, 0xd4, 0xa8, 0x91, 0xcf, 0x30, 0x5a, 0x75, 0xb6,
	0x93, 0x34, 0xdd, 0xeb, 0xee, 0xc9, 0xf8, 0xe5, 0xc1, 0x46, 0xd4, 0xc7, 0x78, 0x47, 0xe1, 0x0c,
	0x9c, 0x9f, 0x6a, 0x3f, 0xf1, 0x7f, 0x97, 0x30, 0xc4, 0x65, 0x35, 0x7f, 0x7b, 0x6e, 0xbe, 0x6a,
	0xad, 0xf0, 0xf8, 0x60, 0x94, 0xbd, 0xa3, 0xd9, 0x87, 0xef, 0xef, 0x93, 0x4c, 0xa6, 0x55, 0xec,
	0x6f, 0x8a, 0x7d, 0x90, 0x3e, 0x94, 0x8c, 0xef, 0xd8, 0x36, 0x61, 0x3c, 0xb8, 0xa3, 0x31, 0xcf,
	0x36, 0xf5, 0xed, 0x20, 0x02, 0x75, 0x9d, 0xc4, 0xf5, 0xcd, 0xf1, 0xf1, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x70, 0x3f, 0x68, 0x1b, 0x5d, 0x04, 0x00, 0x00,
}
