// Code generated by protoc-gen-go.
// source: peer/server_supervise.proto
// DO NOT EDIT!

package peer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PeerReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PeerReply) Reset()                    { *m = PeerReply{} }
func (m *PeerReply) String() string            { return proto.CompactTextString(m) }
func (*PeerReply) ProtoMessage()               {}
func (*PeerReply) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{0} }

type ConnectPeer struct {
	Endpoint string `protobuf:"bytes,1,opt,name=Endpoint" json:"Endpoint,omitempty"`
	Metadata []byte `protobuf:"bytes,2,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	PKIid    []byte `protobuf:"bytes,3,opt,name=PKIid,proto3" json:"PKIid,omitempty"`
}

func (m *ConnectPeer) Reset()                    { *m = ConnectPeer{} }
func (m *ConnectPeer) String() string            { return proto.CompactTextString(m) }
func (*ConnectPeer) ProtoMessage()               {}
func (*ConnectPeer) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{1} }

type PeerInfo struct {
	PeerHeight   uint64         `protobuf:"varint,1,opt,name=peerHeight" json:"peerHeight,omitempty"`
	PeerEndpoint *PeerEndpoint  `protobuf:"bytes,2,opt,name=peerEndpoint" json:"peerEndpoint,omitempty"`
	ConnectPeers []*ConnectPeer `protobuf:"bytes,3,rep,name=connectPeers" json:"connectPeers,omitempty"`
}

func (m *PeerInfo) Reset()                    { *m = PeerInfo{} }
func (m *PeerInfo) String() string            { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()               {}
func (*PeerInfo) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{2} }

func (m *PeerInfo) GetPeerEndpoint() *PeerEndpoint {
	if m != nil {
		return m.PeerEndpoint
	}
	return nil
}

func (m *PeerInfo) GetConnectPeers() []*ConnectPeer {
	if m != nil {
		return m.ConnectPeers
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerReply)(nil), "protos.PeerReply")
	proto.RegisterType((*ConnectPeer)(nil), "protos.ConnectPeer")
	proto.RegisterType((*PeerInfo)(nil), "protos.PeerInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Supervise service

type SuperviseClient interface {
	GetPeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*PeerReply, error)
}

type superviseClient struct {
	cc *grpc.ClientConn
}

func NewSuperviseClient(cc *grpc.ClientConn) SuperviseClient {
	return &superviseClient{cc}
}

func (c *superviseClient) GetPeer(ctx context.Context, in *PeerInfo, opts ...grpc.CallOption) (*PeerReply, error) {
	out := new(PeerReply)
	err := grpc.Invoke(ctx, "/protos.Supervise/GetPeer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Supervise service

type SuperviseServer interface {
	GetPeer(context.Context, *PeerInfo) (*PeerReply, error)
}

func RegisterSuperviseServer(s *grpc.Server, srv SuperviseServer) {
	s.RegisterService(&_Supervise_serviceDesc, srv)
}

func _Supervise_GetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperviseServer).GetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Supervise/GetPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperviseServer).GetPeer(ctx, req.(*PeerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Supervise_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Supervise",
	HandlerType: (*SuperviseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeer",
			Handler:    _Supervise_GetPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor14,
}

func init() { proto.RegisterFile("peer/server_supervise.proto", fileDescriptor14) }

var fileDescriptor14 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x51, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xe5, 0x57, 0xb5, 0xed, 0xb4, 0x07, 0xbb, 0xf6, 0x10, 0x52, 0x90, 0x12, 0x10, 0x2a,
	0x42, 0x23, 0xf5, 0xa0, 0x17, 0x2f, 0x8a, 0x68, 0x11, 0xa1, 0xac, 0x37, 0x3d, 0x48, 0xfe, 0x4c,
	0xb7, 0x0b, 0x6d, 0x76, 0xd9, 0xdd, 0x14, 0xf2, 0x61, 0xfc, 0xae, 0xb2, 0x59, 0x13, 0xd3, 0xd3,
	0xf2, 0xe6, 0xbd, 0x9d, 0x99, 0x37, 0x0f, 0x26, 0x12, 0x51, 0x45, 0x1a, 0xd5, 0x1e, 0xd5, 0x97,
	0x2e, 0x24, 0xaa, 0x3d, 0xd7, 0x38, 0x97, 0x4a, 0x18, 0x41, 0x4e, 0xaa, 0x47, 0x07, 0xa3, 0x4a,
	0xb4, 0x8e, 0x13, 0xc5, 0x53, 0x47, 0x05, 0x13, 0x26, 0x04, 0xdb, 0x62, 0x54, 0xa1, 0xa4, 0x58,
	0x47, 0xb8, 0x93, 0xa6, 0x74, 0x64, 0x78, 0x01, 0xfd, 0x15, 0xa2, 0xa2, 0x28, 0xb7, 0x25, 0xf1,
	0xa1, 0xbb, 0x43, 0xad, 0x63, 0x86, 0xbe, 0x37, 0xf5, 0x66, 0x7d, 0x5a, 0xc3, 0xf0, 0x13, 0x06,
	0x8f, 0x22, 0xcf, 0x31, 0x35, 0x56, 0x4d, 0x02, 0xe8, 0x3d, 0xe5, 0x99, 0x14, 0x3c, 0x37, 0xbf,
	0xca, 0x06, 0x5b, 0xee, 0x0d, 0x4d, 0x9c, 0xc5, 0x26, 0xf6, 0xff, 0x4f, 0xbd, 0xd9, 0x90, 0x36,
	0x98, 0x8c, 0xe1, 0x78, 0xf5, 0xba, 0xe4, 0x99, 0xdf, 0xa9, 0x08, 0x07, 0xc2, 0x6f, 0x0f, 0x7a,
	0xb6, 0xed, 0x32, 0x5f, 0x0b, 0x72, 0x0e, 0x60, 0x2d, 0xbc, 0x20, 0x67, 0x1b, 0xd7, 0xfc, 0x88,
	0xb6, 0x2a, 0xe4, 0x0e, 0x86, 0x16, 0x35, 0xe3, 0xed, 0x88, 0xc1, 0x62, 0xec, 0xec, 0xe8, 0xf9,
	0xaa, 0xc5, 0xd1, 0x03, 0x25, 0xb9, 0x85, 0x61, 0xfa, 0xe7, 0x41, 0xfb, 0x9d, 0x69, 0x67, 0x36,
	0x58, 0x9c, 0xd5, 0x3f, 0x5b, 0xfe, 0xe8, 0x81, 0x70, 0x71, 0x0f, 0xfd, 0xf7, 0xfa, 0xdc, 0xe4,
	0x1a, 0xba, 0xcf, 0xe8, 0xae, 0x70, 0xda, 0x1e, 0x6a, 0x97, 0x0f, 0x46, 0xed, 0x4a, 0x75, 0xd3,
	0xf0, 0xdf, 0xc3, 0xd5, 0xc7, 0x25, 0xe3, 0x66, 0x53, 0x24, 0xf3, 0x54, 0xec, 0xa2, 0x4d, 0x29,
	0x51, 0x6d, 0x31, 0x63, 0x4d, 0x4c, 0x2e, 0x18, 0x1d, 0xd9, 0x65, 0x13, 0x97, 0xe3, 0xcd, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0xa4, 0x3e, 0x23, 0xed, 0x01, 0x00, 0x00,
}
