version: '2'
services:
  zookeeper:
    # Offical Apache ZooKeeper image. See https://hub.docker.com/_/zookeeper/
    image: zookeeper:3.4.9

  orderer:
    build: ./orderer
    environment:
      - ORDERER_GENERAL_QUEUESIZE=1000
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENESIS_ORDERERTYPE=kafka
    ports:
      - '7050'
    depends_on:
      - zookeeper
      - kafka

  kafka:
    build: ../kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
