version: "2"

services:

  membersrvc0:
    extends:
      file: compose-defaults.yml
      service: membersrvc

  orderer0:
    extends:
      file: docker-compose-orderer-solo.yml
      service: orderer0


  vp0:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    depends_on:
      - membersrvc0
      - orderer0
    # ports:
    #   - 7050:6060


  vp1:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_SECURITY_ENROLLID=test_vp1
      - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
    depends_on:
      - membersrvc0
      - orderer0
      - vp0

  vp2:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_SECURITY_ENROLLID=test_vp2
      - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
    depends_on:
      - membersrvc0
      - orderer0
      - vp0

  vp3:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_SECURITY_ENROLLID=test_vp3
      - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
    depends_on:
      - membersrvc0
      - orderer0
      - vp0
