FROM hyperledger/fabric-baseos:_BASE_TAG_
ENV ORDERER_CFG_PATH /etc/hyperledger/fabric
RUN mkdir -p /var/hyperledger/production $ORDERER_CFG_PATH
COPY payload/orderer /usr/local/bin
COPY payload/genesis.yaml $ORDERER_CFG_PATH/
COPY payload/orderer.yaml $ORDERER_CFG_PATH/
COPY payload/genesis.yaml $ORDERER_CFG_PATH/
RUN mkdir -p /etc/hyperledger/fabric/orderer/src/github.com/hyperledger/fabric/common/configtx/tool/
COPY payload/genesis.yaml /etc/hyperledger/fabric/orderer/src/github.com/hyperledger/fabric/common/configtx/tool/
EXPOSE 7050
CMD orderer
